// Generated by CoffeeScript 1.8.0
(function() {
  (function(e, a, g, h, f, c, b, d) {
    if (!(f = e.jQuery) || g > f.fn.jquery || h(f)) {
      c = a.createElement("script");
      c.type = "text/javascript";
      c.src = "http://ajax.googleapis.com/ajax/libs/jquery/" + g + "/jquery.min.js";
      c.onload = c.onreadystatechange = function() {
        if (!b && (!(d = this.readyState) || d === "loaded" || d === "complete")) {
          h((f = e.jQuery).noConflict(1), b = 1);
          return f(c).remove();
        }
      };
      return a.documentElement.childNodes[0].appendChild(c);
    }
  })(window, document, "2.1.3", function($, L) {
    var url;
    url = window.location.href;
    return $.ajax({
      method: "POST",
      data: {
        url: url
      },
      url: "https://todiffer.herokuapp.com/articles",
      success: function() {
        return alert('Now tracking this article');
      }
    });
  });

}).call(this);
