// Generated by CoffeeScript 1.8.0
(function() {
  (function(e, a, g, h, f, c, b, d) {
    if (!(f = e.jQuery) || g > f.fn.jquery || h(f)) {
      c = a.createElement("script");
      c.type = "text/javascript";
      c.src = "http://ajax.googleapis.com/ajax/libs/jquery/" + g + "/jquery.min.js";
      c.onload = c.onreadystatechange = function() {
        if (!b && (!(d = this.readyState) || d === "loaded" || d === "complete")) {
          h((f = e.jQuery).noConflict(1), b = 1);
          return f(c).remove();
        }
      };
      return document.body.appendChild(c);
    }
  })(window, document, "2.1.3", function($, L) {
    var injectStyles, prevElement, submitStory;
    injectStyles = function(rule) {
      var div;
      return div = $("<div />", {
        html: '&shy;<style>' + rule + '</style>'
      }).appendTo("body");
    };
    injectStyles('.mouseOn { background: #bcd5eb !important; outline: 2px solid #5166bb !important; }');
    prevElement = null;
    document.addEventListener('mousemove', function(e) {
      var $el, elem;
      elem = e.target || e.srcElement;
      $el = $(elem);
      if (prevElement !== null) {
        prevElement.classList.remove("mouseOn");
      }
      elem.classList.add("mouseOn");
      $(elem).on('click', function() {
        return submitStory;
      });
      $(prevElement).off('click', function() {
        return submitStory;
      });
      return prevElement = elem;
    }, true);
    return submitStory = function() {
      debugger;
      return $.ajax({
        method: "POST",
        data: {
          url: url
        },
        url: "https://todiffer.herokuapp.com/articles",
        success: function() {
          return alert('Now tracking this article');
        }
      });
    };
  });

}).call(this);
